[project]
name = "rnn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
    "scikit-learn>=1.7.2",
    "torch==2.2.2",
    "tqdm>=4.67.3",
    "numpy<2"
]
